apiVersion: apps/v1
kind: Deployment
metadata:
  name: nulog-inference-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nulog-inference-service
  template:
    metadata:
      labels:
        app: nulog-inference-service
    spec:
      containers:
      - name: nulog-inference-service
        image: tybalex/nulog-inference-service
        imagePullPolicy: Always
        env:
        - name: NATS_SERVER_URL
          value: "nats://nats_client:%NATS_PASSWORD%@nats-client.kube-system.svc:4222"
        - name: ES_ENDPOINT
          value: "https://opendistro-es-client-service.default.svc.cluster.local:9200"
        - name: MINIO_ACCESS_KEY
          value: "%MINIO_ACCESS_KEY%"
        - name: MINIO_SECRET_KEY
          value: "%MINIO_SECRET_KEY%"
        resources:
          limits:
            nvidia.com/gpu: 1
