apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik 
  namespace: opni-system
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  version: "%TRAEFIK_VERSION%"
  set:
    ports.websecure.nodePort: 32222 # hardcoding node port for traefik endpoint to be used later in rancher logging